### ISSUE TITLE
CUDA drivers not installed

### ISSUE THREAD

**Issue by dopplesoldner** [wbuchwalter/blog-posts#1]
Thanks for the helpful blog post. I was able to get a cluster running using the steps outlined however the nodes didn't have nvidia drivers installed so was unable to get the training working.

Is there a way to specify images for the kubernetes nodes with nvidia drivers installed?

**Comment by wbuchwalter** [comment]
Hi,
I'm assuming the issue you are talking about is this one:
`ImportError: libcudnn.5: cannot open shared object file: No such file or directory`.

I haven't had time to really dig into it, it's an issue that has come up recently with the newest cuda docker images.  
What is happening is that the mount on `/usr/lib/x86_64-linux-gnu` is overwriting `libcuddn.5`.  
You could install cuda/cuDNN on each host node, but that is a pretty long and cumbersome process. 
Instead, an easy fix is to change the mount path to something like `/usr/lib/x86_64-linux-gnu_custom`, and add this new path to the ` LD_LIBRARY_PATH`.
[Here is an example](https://github.com/wbuchwalter/tensorflow-cyclegan/blob/master/k8s/train.yaml) of what the new kubernetes template would look like.

**Comment by wbuchwalter** [comment]
Assuming this fixed your issue.

**Comment by dopplesoldner** [comment]
Thanks @wbuchwalter. Yes the issue was as you mentioned - my libs were being overwritten due to the mountpoints. I eventually faced the same issue with `/bin` path as I needed `ffmpeg` in my container. I was able to resolve using custom paths and adding them to the required env variables.
